import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight, ArrowDown, GithubLogo, Sun, Moon, List, X, Plus, Minus, DownloadSimple, Play, CornersOut, Code, TreeStructure, Sparkle, ChartLineUp, Check, Copy} from '@phosphor-icons/react';
import '@fontsource-variable/manrope';
import {profile,projects,explorations,experiences,skills,awards} from './content';
import './styles.css';
const asset=(path)=>`${import.meta.env.BASE_URL}${path}`;
const photo=(path)=>asset(`projects/${path}`);
const nav=[['作品','work'],['AI 技能','skills'],['关于我','about'],['荣誉','awards']];
const icons=[Code,TreeStructure,Sparkle,ChartLineUp];
function OutLink({href,children,className=''}){return <a href={href} target="_blank" rel="noreferrer" className={className}>{children}<ArrowUpRight size={18}/></a>}
function App(){
 const [menu,setMenu]=useState(false);const [theme,setTheme]=useState(()=>document.documentElement.dataset.theme==='dark'?'dark':'light');
 const [filter,setFilter]=useState('全部作品');const [selected,setSelected]=useState(null);const [slide,setSlide]=useState(0);const [video,setVideo]=useState(false);const [copied,setCopied]=useState(false);const [active,setActive]=useState('');
 const dialog=useRef(null);const copyTimer=useRef(null);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)setActive(e.target.id)})},{rootMargin:'-15% 0px -55% 0px'});document.querySelectorAll('main section[id]').forEach(e=>observer.observe(e));return()=>{observer.disconnect();clearTimeout(copyTimer.current)}},[]);
 useEffect(()=>{if(selected){dialog.current?.showModal();document.body.style.overflow='hidden'}else{dialog.current?.close();document.body.style.overflow=''}return()=>{document.body.style.overflow=''}},[selected]);
 useEffect(()=>{const media=matchMedia('(prefers-color-scheme: dark)');const update=e=>{try{if(localStorage.getItem('peilin-theme'))return}catch{}const next=e.matches?'dark':'light';setTheme(next);document.documentElement.dataset.theme=next};media.addEventListener('change',update);return()=>media.removeEventListener('change',update)},[]);
 const toggleTheme=()=>{const next=theme==='dark'?'light':'dark';setTheme(next);document.documentElement.dataset.theme=next;try{localStorage.setItem('peilin-theme',next)}catch{}};
 const openProject=(project,play=false)=>{setSlide(0);setVideo(play);setSelected(project)};
 const closeProject=()=>{setSelected(null);setVideo(false)};
 const copyEmail=async()=>{try{await navigator.clipboard.writeText(profile.email);setCopied(true);clearTimeout(copyTimer.current);copyTimer.current=setTimeout(()=>setCopied(false),2200)}catch{window.location.href=`mailto:${profile.email}`}};
 const visible=filter==='全部作品'?projects:projects.filter(p=>p.category===filter);
 return <>
  <a className="skip-link" href="#main">跳到主要内容</a>
  <header className="site-header"><div className="nav-shell">
   <a href="#home" className="brand" aria-label="P. PEILIN XIE 谢沛霖，返回首页"><span className="brand-symbol">P<span>.</span></span><span>PEILIN XIE<span className="brand-cn">谢沛霖</span></span></a>
   <nav className={menu?'navigation is-open':'navigation'} aria-label="主导航">{nav.map(([label,id])=><a key={id} className={active===id?'active':''} href={`#${id}`} onClick={()=>setMenu(false)}>{label}</a>)}<a className="mobile-contact" href="#contact" onClick={()=>setMenu(false)}>联系我 <ArrowUpRight/></a></nav>
   <div className="nav-actions"><button className="icon-button theme-toggle" onClick={toggleTheme} aria-label={theme==='light'?'切换为深色模式':'切换为浅色模式'}>{theme==='light'?<Moon size={20}/>:<Sun size={20}/>}</button><a href="#contact" className="nav-contact">聊一聊 <ArrowUpRight size={17}/></a><button className="icon-button menu-toggle" aria-label={menu?'关闭导航':'打开导航'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<List/>}</button></div>
  </div></header>
  <main id="main">
   <section id="home" className="hero section-shell">
    <div className="hero-copy"><p className="eyebrow">DATA MIND. BUILDER SPIRIT.</p><div className="intro-name">你好，我是谢沛霖 <span className="greeting-stroke" aria-hidden="true">✳</span></div><h1>用数据理解问题，<br/>用 AI <span>把想法做出来。</span></h1><p className="hero-description">同济大学管理科学与工程硕士。<br/>在数据科学与 AI 应用之间，探索从洞察到产品的更多可能。</p><div className="hero-actions"><a className="button primary" href="#work">探索我的作品 <ArrowDown size={18}/></a><a className="text-link" href={asset('Peilin-Xie-Resume.pdf')} target="_blank" rel="noreferrer">查看简历 <ArrowUpRight size={18}/></a></div><div className="hero-meta"><span>同济大学 <small>硕士 / 2027 届</small></span><span>上海 <small>AI 应用 × 数据科学</small></span></div></div>
    <div className="hero-visual"><div className="visual-grid" aria-hidden="true"/><span className="visual-word" aria-hidden="true">MAKE<br/>IT REAL.</span><button className="hero-shot shot-back" onClick={()=>openProject(projects[1])} aria-label="查看 WorkRelay 项目"><img src={photo('workrelay.webp')} alt="WorkRelay 项目决策工作台" width="1440" height="1000"/><span>WorkRelay <ArrowUpRight/></span></button><button className="hero-shot shot-front" onClick={()=>openProject(projects[0])} aria-label="查看智帧华象项目"><img src={photo('lumiframe.webp')} alt="智帧华象的创作展厅" width="1440" height="1000" fetchPriority="high"/><span>智帧华象 <ArrowUpRight/></span></button><div className="visual-caption"><span className="small-cross" aria-hidden="true">+</span><span>FROM CURIOSITY<br/><strong>TO SOMETHING REAL</strong></span></div></div>
   </section>
   <div className="experience-strip section-shell"><span className="strip-label">让想法经得起实践</span><div className="company-word jd">JD<span>京东科技</span></div><div className="company-word ebay">ebay</div><div className="company-word hello">哈啰 <span>Hello</span></div><span className="strip-note">数据分析与数据科学实习经历</span></div>
   <section id="work" className="work section-shell"><div className="section-heading"><div><p className="eyebrow">SELECTED WORK</p><h2>想法，已落地。</h2></div><p>因为好奇而开始，因为真实的问题而持续迭代。<br/>这是我的 Vibe Coding 实践记录。</p></div>
    <div className="filter-bar" aria-label="作品分类">{['全部作品','AI 应用','Agent','数据工具'].map(item=><button key={item} className={filter===item?'selected':''} aria-pressed={filter===item} onClick={()=>setFilter(item)}>{item}{item==='全部作品'&&<span>{projects.length}</span>}</button>)}<span className="filter-note">从需求到可以体验的产品 <ArrowDown size={14}/></span></div>
    <div className="project-list">{visible.map(p=><article className="project" key={p.id} id={`project-${p.id}`}>
     <button className={`project-preview preview-${p.id}`} style={{'--preview-bg':p.background}} onClick={()=>openProject(p)} aria-label={`${p.english} ${p.category} 查看项目：${p.name}截图与详情`}><div className="preview-heading"><span>{p.english}</span><CornersOut size={18}/></div><div className="screenshot-frame"><img src={photo(p.image)} alt={`${p.name}：${p.imageLabels[0]}`} width="1440" height="1000" loading="lazy"/></div><div className="preview-foot"><span>{p.category}</span><span>查看项目 <ArrowUpRight size={15}/></span></div></button>
     <div className="project-copy"><div className="project-topline"><span>{p.category}</span><span>{p.state}</span></div><h3>{p.name}</h3><p className="project-tagline">{p.tagline}</p><p className="project-description">{p.description}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><div className="project-links"><button className="text-link" onClick={()=>openProject(p)}>了解项目 <ArrowUpRight size={18}/></button>{p.url&&<OutLink href={p.url}>在线体验</OutLink>}{p.repo&&<OutLink href={p.repo}>GitHub</OutLink>}{p.video&&<button className="text-link muted" onClick={()=>openProject(p,true)}><Play size={15}/> 演示</button>}</div></div>
    </article>)}</div>
    <div className="explorations"><div className="explore-intro"><p className="eyebrow">ALWAYS EXPLORING</p><h3>还有一些，<br/>好奇心的产物。</h3><p>小程序、数据产品、品牌页面和交互实验。<br/>每一次动手，都是一次新的理解。</p></div><div className="explore-list">{explorations.map(p=><details key={p.name}><summary><span>{p.name}</span><span className="explore-type">{p.type}</span><Plus className="detail-plus" size={19}/><Minus className="detail-minus" size={19}/></summary><div className="explore-detail"><p>{p.text}</p>{p.repo&&<OutLink href={p.repo}>查看 GitHub 项目</OutLink>}</div></details>)}</div></div>
   </section>
   <section id="skills" className="skills-section"><div className="section-shell"><div className="section-heading"><div><p className="eyebrow">MY TOOLKIT</p><h2>把 AI 用在，<br/>真正有用的地方。</h2></div><p>不只停留在对话。<br/>从产品实现到工作流设计，再到结果验证。</p></div><div className="skill-grid">{skills.map((s,i)=>{const Icon=icons[i];return <article className="skill-item" key={s.title}><div className="skill-top"><Icon size={28} weight="light"/><span>{s.english}</span></div><h3>{s.title}</h3><p>{s.text}</p><ul>{s.items.map(t=><li key={t}>{t}</li>)}</ul><div className="skill-evidence"><span>实践于</span>{s.evidence}</div></article>})}</div></div></section>
   <section id="about" className="about section-shell"><div className="section-heading"><div><p className="eyebrow">A LITTLE ABOUT ME</p><h2>理性分析，也热衷创造。</h2></div><a className="text-link" href={asset('Peilin-Xie-Resume.pdf')} download>下载完整简历 <DownloadSimple size={19}/></a></div><div className="about-intro"><div className="name-block"><span>谢沛霖</span><strong>Peilin<br/>Xie<span>.</span></strong><p>DATA SCIENCE<br/>AI APPLICATION<br/>CONTINUOUS CURIOSITY</p></div><div className="about-story"><p>我的起点是管理科学与工程，<br/>兴趣始终围绕一件事：<strong>让复杂问题变得可理解、可解决。</strong></p><p>在京东科技、eBay 和哈啰出行的实习中，我用数据理解用户、评估策略。工作之外，我把这些问题意识带进 AI 应用开发，亲手搭建工具，再通过使用和反馈不断完善。</p><p>我喜欢从一个具体需求开始，走完「理解问题 → 做出原型 → 验证效果 → 持续改进」的过程。</p><div className="education"><article><div><h3>同济大学</h3><span>经济与管理学院</span></div><p>管理科学与工程<br/>工业工程与管理硕士</p><div className="edu-meta"><span>2024.09 - 2027.03</span><strong>GPA 4.8/5.0 · Top 1%</strong></div></article><article><div><h3>苏州大学</h3><span>管理学院</span></div><p>管理科学与工程<br/>物流管理与工程</p><div className="edu-meta"><span>2020.09 - 2024.06</span><strong>GPA 4.0/4.0 · 专业 1/95</strong></div></article></div></div></div>
    <div className="experience-heading"><h3>在真实业务中，验证想法。</h3><span>实习经历</span></div><div className="experience-list">{experiences.map(e=><details className="experience-row" key={e.company}><summary><div className="experience-company"><h4>{e.company}</h4><span>{e.team}</span></div><div className="experience-summary"><strong>{e.role}</strong><p>{e.text}</p><div className="experience-metrics"><span>{e.metric}</span><span>{e.metric2}</span></div></div><span className="experience-date">{e.date.replace('—','-')}</span><Plus className="detail-plus" size={20}/><Minus className="detail-minus" size={20}/></summary><div className="experience-expanded"><ul>{e.details.map(d=><li key={d}>{d}</li>)}</ul></div></details>)}</div><p className="source-note">实习职责与成果根据个人简历整理。</p>
    <details className="case-study"><summary><span>业务案例</span><strong>社区直播场域重构：从 A/B 实验到异质性策略</strong><Plus className="detail-plus"/><Minus className="detail-minus"/></summary><div><p>针对京东金融社区内容定位与留存问题，从迁移用户规模测算出发，搭建 SQL 哈希分桶与 AA 校验，再开展灰度 A/B 实验。通过 Causal Forest 识别不同用户的异质性收益，协同算法与运营迭代推荐和内容策略。</p><div className="case-results"><p><strong>+2.1pp</strong><span>社区次日留存</span></p><p><strong>+35%</strong><span>直播 Tab 渗透率</span></p><p><strong>近 60%</strong><span>大 V 跟投 GMV 环比增长</span></p></div></div></details>
   </section>
   <section id="awards" className="awards-section section-shell"><div className="awards-intro"><p className="eyebrow">RECOGNITION</p><h2>努力的，<br/>一些注脚。</h2><p>在学术、建模与创新实践中，<br/>持续拓展能力的边界。</p><div className="award-monogram" aria-hidden="true">✳</div></div><div className="award-list">{awards.map(([title,type])=><article key={title}><h3>{title}</h3><span>{type}</span></article>)}<div className="certificates"><span>ACCA 高级商业会计证书</span><span>IELTS 6.5</span><span>CET-6 568</span></div></div></section>
   <section id="contact" className="contact-section"><div className="section-shell contact-inner"><div><p className="eyebrow">LET’S MAKE SOMETHING USEFUL.</p><h2>下一个好想法，<br/>一起实现。</h2><p>关于 AI 应用、数据科学，或一个值得尝试的想法，<br/>欢迎来聊聊。</p></div><div className="contact-actions"><a className="email-link" href={`mailto:${profile.email}`}>Say hello <ArrowUpRight weight="light"/></a><div className="email-address"><a href={`mailto:${profile.email}`}>{profile.email}</a><button className="icon-button" onClick={copyEmail} aria-label={copied?'邮箱已复制':'复制邮箱'}>{copied?<Check size={19}/>:<Copy size={19}/>}</button><span className="sr-only" role="status">{copied?'邮箱已复制':''}</span></div><div className="contact-links"><OutLink href={profile.github}><GithubLogo size={19}/> GitHub</OutLink><a href={asset('Peilin-Xie-Resume.pdf')} target="_blank" rel="noreferrer">个人简历 <ArrowUpRight size={18}/></a></div></div></div><footer className="section-shell"><span>© {new Date().getFullYear()} Peilin Xie</span><span>保持好奇，持续创造。</span><a href="#home">回到顶部 <ArrowUpRight size={16}/></a></footer></section>
  </main>
  <dialog ref={dialog} className="project-dialog" onCancel={closeProject} onClose={()=>{if(selected)closeProject()}} onClick={e=>{if(e.target===e.currentTarget)closeProject()}} aria-labelledby="dialog-title">{selected&&<><div className="dialog-header"><div><span>{selected.category}</span><h2 id="dialog-title">{selected.name}</h2></div><button className="icon-button" onClick={closeProject} autoFocus aria-label="关闭项目详情"><X size={23}/></button></div><div className="dialog-content"><div className="dialog-media">{video&&selected.video?<video controls autoPlay playsInline preload="metadata" src={photo(selected.video)} poster={photo(selected.image)} aria-label={`${selected.name}项目演示`}/>:<img src={photo(selected.images[slide])} alt={`${selected.name}：${selected.imageLabels[slide]}`}/>}</div><div className="dialog-media-controls"><span>{video?'项目演示视频':selected.imageLabels[slide]}</span><div>{selected.images.length>1&&selected.images.map((_,i)=><button key={i} onClick={()=>{setVideo(false);setSlide(i)}} className={slide===i&&!video?'selected':''}>{selected.imageLabels[i]}</button>)}{selected.video&&<button className={video?'selected':''} onClick={()=>setVideo(!video)}>{video?'查看截图':'播放演示'}</button>}</div></div><div className="dialog-description"><p className="dialog-tagline">{selected.tagline}</p><div className="case-columns"><div><h3>从什么问题出发</h3><p>{selected.problem}</p></div><div><h3>如何实现</h3><p>{selected.approach}</p></div></div><h3>主要能力</h3><ul>{selected.features.map(f=><li key={f}>{f}</li>)}</ul><div className="project-boundary"><h3>当前状态</h3><p>{selected.boundary}</p></div><p className="stack">{selected.stack}</p><div className="dialog-links">{selected.url&&<OutLink className="button primary" href={selected.url}>打开在线应用</OutLink>}{selected.repo&&<OutLink className="button primary" href={selected.repo}>查看 GitHub 项目</OutLink>}<button className="button secondary" onClick={closeProject}>返回作品集</button></div></div></div></>}</dialog>
 </>
}
createRoot(document.getElementById('root')).render(<App/>);
